CREATE TABLE `tbl_stations` (
  `STATION_ID` char(32) NOT NULL,
  `STATION_NAME` char(32) DEFAULT NULL,
  `LAST_DATE_OF_REPAIR` datetime DEFAULT NULL,
  PRIMARY KEY (`STATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
