CREATE TABLE `tbl_administrator` (
  `ADMIN_ID` char(32) NOT NULL,
  `NAME` char(32) NOT NULL,
  `PASSWORD` char(128) COLLATE utf8_unicode_ci NOT NULL,
  `CONTACT_NO` char(32) DEFAULT NULL,
  `LAST_ACCESSED_TIME` datetime DEFAULT NULL,
  `NIC` char(32) DEFAULT NULL,
  `DESIGNATION` char(64) DEFAULT NULL,
   PRIMARY KEY (`ADMIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
