CREATE TABLE `tbl_river_node` (
  `NODE_ID` char(32) COLLATE utf8_unicode_ci NOT NULL,
  
  `CURRENT_LEVEL` smallint DEFAULT NULL,
  `ALERT_LEVEL` smallint DEFAULT NULL,
  `MINOR_FLOOD_LEVEL` smallint DEFAULT NULL,
  `MAJOR_FLOOD_LEVEL` smallint DEFAULT NULL,
  `RECORDED_HIGHEST_LEVEL` smallint DEFAULT NULL,
  `STATION_ID` char(32) ,
  PRIMARY KEY (`NODE_ID`)
  
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
